
"""“Master thesis code”

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r6BQShVUx89eOB0fZGyH8kI6WDs6Mdl7
"""


!python "/content/prott5_embedder.py" --input "/content/DNA_Test_129.fa" --output residue_embeddings_573.h5

import h5py
import pandas as pd


def load_txt_data(txt_filepath):
    with open(txt_filepath, 'r') as file:
        lines = file.readlines()

    data = []
    for i in range(0, len(lines), 3):
        protein_id = lines[i].strip()[1:]  
        sequence = lines[i+1].strip()
        label = lines[i+2].strip()
        data.append({'Protein ID': protein_id, 'Sequence': sequence, 'Label': label})

    return pd.DataFrame(data)


def load_h5_data(h5_filepath, protein_ids):
    features = {}
    with h5py.File(h5_filepath, 'r') as hdf:
        for protein_id in protein_ids:
            if protein_id in hdf:
                features[protein_id] = hdf[protein_id][:]  

    return features


def merge_data(txt_df, h5_features):

    feature_rows = []
    for index, row in txt_df.iterrows():
        protein_id = row['Protein ID']
        if protein_id in h5_features:
            feature_vector = h5_features[protein_id].flatten() 
            feature_rows.append(pd.Series([row['Label']] + feature_vector.tolist()))


    if feature_rows:
        feature_df = pd.DataFrame(feature_rows)
        feature_df.columns = ['Label'] + [f'Feature_{i}' for i in range(feature_df.shape[1] - 1)]
        return feature_df
    else:
        return pd.DataFrame()

import h5py


file_path = '/content/residue_embeddings_573.h5'
with h5py.File(file_path, 'r') as f:

    def print_structure(name, obj):
        if isinstance(obj, h5py.Dataset):
            print(f"Dataset: {name}, Shape: {obj.shape}, Dtype: {obj.dtype}")
        elif isinstance(obj, h5py.Group):
            print(f"Group: {name}")

    f.visititems(print_structure)

import h5py
import pandas as pd
import csv


txt_file_path = "/content/DNA-129_Test.txt"
h5_file_path = "/content/residue_embeddings_129.h5"
output_file_path = "merged_output.csv"


def read_txt_file(file_path):
    labels = []
    protein_ids = []
    with open(file_path, "r") as f:
        lines = f.readlines()
        for i in range(0, len(lines), 3):
            protein_id = lines[i].strip()[1:]
            label = int(lines[i + 2].strip()[0])
            labels.append(label)
            protein_ids.append(protein_id)
    return pd.DataFrame({"Label": labels, "ProteinID": protein_ids})

def read_h5_file(file_path):
    with h5py.File(file_path, "r") as h5_file:
        return {key: h5_file[key][:] for key in h5_file.keys()}

def merge_data(txt_data, h5_data):
    merged_data = []
    for idx, row in txt_data.iterrows():
        protein_id = row["ProteinID"]
        label = row["Label"]
        if protein_id in h5_data:
            features = h5_data[protein_id]
            for feature_row in features:
                merged_data.append([label, protein_id] + feature_row.tolist())

        if idx < 3:
            print(f"Protein ID: {protein_id}")
            print(f"Label: {label}")
            if protein_id in h5_data:
                print(f"Feature Shape: {h5_data[protein_id].shape}")
                print(f"First Feature Row: {h5_data[protein_id][0]}")
            else:
                print("Protein ID not found in H5 file.")
            print("=" * 50)

    return merged_data

if __name__ == "__main__":

    print("读取 TXT 文件...")
    txt_data = read_txt_file(txt_file_path)
    print(f"TXT 文件前 3 行: \n{txt_data.head(3)}\n")

    print("读取 H5 文件...")
    h5_data = read_h5_file(h5_file_path)
    print(f"H5 文件中蛋白数量: {len(h5_data)}")

    print("合并数据...")
    merged_data = merge_data(txt_data, h5_data)

    print(f"合并数据的前 5 行: \n")
    for row in merged_data[:5]:
        print(row)

    if input("格式检查完成？输入 'yes' 确认保存: ").strip().lower() == "yes":

        columns = ["Label", "ProteinID"] + [f"Feature_{i}" for i in range(1024)]
        with open(output_file_path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(columns)
            writer.writerows(merged_data)

        print(f"数据已合并并保存到 {output_file_path}")
    else:
        print("数据未保存，请修正格式后重试。")

print(data.head())

"""

import torch
import pandas as pd
D_feature = pd.read_csv("/content/drive/MyDrive/merged_output_573.csv")

feature_y_Benchmark_embeddings = D_feature.iloc[:, 0].values
feature_X_Benchmark_embeddings = np.zeros((feature_y_Benchmark_embeddings.shape[0], 1), dtype=float)
feature_X_Benchmark_embeddings = np.concatenate((feature_X_Benchmark_embeddings, D_feature.iloc[:, 0:].values), axis=1)
feature_X_Benchmark_embeddings = np.delete(feature_X_Benchmark_embeddings, 0, axis=1)

feature_X_Benchmark_embeddings_positive = feature_X_Benchmark_embeddings[feature_X_Benchmark_embeddings[:, 0] == 1, 2:]
feature_y_Benchmark_embeddings_positive = feature_X_Benchmark_embeddings[feature_X_Benchmark_embeddings[:, 0] == 1, 0].astype('int')
feature_X_Benchmark_embeddings_negative = feature_X_Benchmark_embeddings[feature_X_Benchmark_embeddings[:, 0] == 0, 2:]
feature_y_Benchmark_embeddings_negative = feature_X_Benchmark_embeddings[feature_X_Benchmark_embeddings[:, 0] == 0, 0].astype('int')

print(feature_X_Benchmark_embeddings.shape)
print(feature_y_Benchmark_embeddings.shape)

print(feature_X_Benchmark_embeddings_positive.shape)
print(feature_y_Benchmark_embeddings_positive.shape)

print(feature_X_Benchmark_embeddings_negative.shape)
print(feature_y_Benchmark_embeddings_negative.shape)

from sklearn.model_selection import train_test_split

feature_X_Benchmark_embeddings_positive_train, feature_X_Benchmark_embeddings_positive_test, feature_y_Benchmark_embeddings_positive_train, feature_y_Benchmark_embeddings_positive_test = train_test_split(feature_X_Benchmark_embeddings_positive, feature_y_Benchmark_embeddings_positive, test_size=0.3, random_state=1)
feature_X_Benchmark_embeddings_negative_train, feature_X_Benchmark_embeddings_negative_test, feature_y_Benchmark_embeddings_negative_train, feature_y_Benchmark_embeddings_negative_test = train_test_split(feature_X_Benchmark_embeddings_negative, feature_y_Benchmark_embeddings_negative, test_size=0.3, random_state=1)

print(feature_X_Benchmark_embeddings_positive_train.shape)
print(feature_X_Benchmark_embeddings_positive_test.shape)

print(feature_X_Benchmark_embeddings_negative_train.shape)
print(feature_X_Benchmark_embeddings_negative_test.shape)

feature_X_Benchmark_embeddings_train = np.concatenate((feature_X_Benchmark_embeddings_positive_train, feature_X_Benchmark_embeddings_negative_train), axis=0)
feature_y_Benchmark_embeddings_train = np.concatenate((feature_y_Benchmark_embeddings_positive_train, feature_y_Benchmark_embeddings_negative_train), axis=0)
feature_X_Benchmark_embeddings_test = np.concatenate((feature_X_Benchmark_embeddings_positive_test, feature_X_Benchmark_embeddings_negative_test), axis=0)
feature_y_Benchmark_embeddings_test = np.concatenate((feature_y_Benchmark_embeddings_positive_test, feature_y_Benchmark_embeddings_negative_test), axis=0)

print(feature_X_Benchmark_embeddings_train.shape)
print(feature_y_Benchmark_embeddings_train.shape)

print(feature_X_Benchmark_embeddings_test.shape)
print(feature_y_Benchmark_embeddings_test.shape)

"""

import pandas as pd
import numpy as np
from imblearn.under_sampling import RandomUnderSampler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split

from xgboost import XGBClassifier

from sklearn.naive_bayes import GaussianNB

import random
import pickle
import csv

from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import KBinsDiscretizer

from sklearn.model_selection import StratifiedKFold
from sklearn.feature_selection import mutual_info_classif
from collections import Counter

def preprocess_the_dataset(feature_X):

    pt = PowerTransformer()
    pt.fit(feature_X)
    feature_X = pt.transform(feature_X)

    return feature_X

def model_fit(model_name, X_train, y_train):
    if model_name == 'RF':
        model = RandomForestClassifier(random_state=1)
    elif model_name == 'ET':
        model = ExtraTreesClassifier(random_state=1)
    elif model_name == 'DT':
        model = DecisionTreeClassifier(random_state=1)
    elif model_name == 'MLP':
        model = MLPClassifier(random_state=1, max_iter=4000)
    elif model_name == 'LR':
        model = LogisticRegression(class_weight='balanced', random_state=1, max_iter=1000)
    elif model_name == 'NB':
        model = GaussianNB()
    elif model_name == 'KNN':
        model = KNeighborsClassifier()
    elif model_name == 'XGB':
        model = XGBClassifier(random_state=1)
    else:
        print('Wrong model name')
        return

    try:
        model.fit(X_train, y_train)

    return model


def make_string(s):
    str = ''
    for i in s:
        str += i + ", "
    return str[:-2]

feature_X_Benchmark_embeddings_train = preprocess_the_dataset(feature_X_Benchmark_embeddings_train)
feature_X_Benchmark_embeddings_test = preprocess_the_dataset(feature_X_Benchmark_embeddings_test)

X = feature_X_Benchmark_embeddings_train.copy()
y = feature_y_Benchmark_embeddings_train.copy()

rus = RandomUnderSampler(random_state=1)
X, y = rus.fit_resample(X, y)

c = Counter(y)
print(c)

probabilities = {}
model_names = ['XGB', 'NB', 'KNN', 'LR','MLP', 'DT', 'RF', 'ET']
for model_name in model_names:
    print(model_name+" model fit is running")
    model = model_fit(model_name, X, y)
    probabilities[model_name] = model.predict_proba(feature_X_Benchmark_embeddings_test)[:, 1].reshape(-1, 1)

with open('./model_wise_MI.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Learner Combination", "MI"])
    for learners in learner_combination:
        print(make_string(learners))
        prob = np.zeros((feature_X_Benchmark_embeddings_test.shape[0], 1), dtype=float)
        for learner in learners:
            prob = np.concatenate((prob, probabilities[learner]), axis=1)
        prob = np.delete(prob, 0, axis=1)

        realProb = np.zeros(prob.shape[0], dtype=float)
        for i in range(prob.shape[0]):
            realProb[i] = np.mean(prob[i])
        MI = mutual_info_classif(realProb.reshape(-1, 1), feature_y_Benchmark_embeddings_test, random_state=1)
        print('{0:.4f}'.format(np.mean(MI)))
        writer.writerow([make_string(learners), '{0:.4f}'.format(np.mean(MI))])

"""

import pandas as pd
import numpy as np
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split

from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB

import random
import pickle
import csv

from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import KBinsDiscretizer

from sklearn.model_selection import StratifiedKFold
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,f1_score,matthews_corrcoef,average_precision_score
from sklearn.metrics import balanced_accuracy_score

def preprocess_the_dataset(feature_X):

    pt = PowerTransformer()
    pt.fit(feature_X)
    feature_X = pt.transform(feature_X)

    return feature_X

def model_fit(model_name, X_train, y_train):
    if model_name == 'RF':
        model = RandomForestClassifier(random_state=1)
    elif model_name == 'ET':
        model = ExtraTreesClassifier(random_state=1)
    elif model_name == 'DT':
        model = DecisionTreeClassifier(random_state=1)
    elif model_name == 'MLP':
        model = MLPClassifier(random_state=1, max_iter=4000)
    elif model_name == 'LR':
        model = LogisticRegression(class_weight='balanced', random_state=1, max_iter=1000)
    elif model_name == 'NB':
        model = GaussianNB()
    elif model_name == 'KNN':
        model = KNeighborsClassifier()
    elif model_name == 'XGB':
        model = XGBClassifier(random_state=1)
    else:
        print('Wrong model name')
        return
        model.fit(X_train, y_train)

    return model


def make_string(s):
    str = ''
    for i in s:
        str += i + ", "
    return str[:-2]

def create_subsample(X, y, percentage):
    X = np.concatenate((y.reshape(-1, 1), X), axis=1)

    feature_X_positive = X[X[:, 0] == 1, 1:]
    feature_y_positive = X[X[:, 0] == 1, 0].astype('int')

    feature_X_negative = X[X[:, 0] == 0, 1:]
    feature_y_negative = X[X[:, 0] == 0, 0].astype('int')

    feature_X_positive_test = feature_X_positive
    feature_y_positive_test = feature_y_positive

    feature_X_negative_train, feature_X_negative_test, feature_y_negative_train, feature_y_negative_test = train_test_split(
        feature_X_negative, feature_y_negative, test_size=percentage, random_state=1)






    feature_X_test = np.concatenate((feature_X_positive_test, feature_X_negative_test), axis=0)
    feature_y_test = np.concatenate((feature_y_positive_test, feature_y_negative_test), axis=0)

    print("subsample shape:",)
    print(feature_X_test.shape)
    print(feature_y_test.shape)

    return feature_X_test, feature_y_test

def create_base_layer(X, y):
    X = preprocess_the_dataset(X)
    percentages = [0.002, 0.002, 0.002, 0.002, 0.02, 0.02, 0.02, 0.2, 0.2, 0.2]
    model_names = ['KNN', 'MLP']

    i = 0
    for percentage in percentages:
        trainX, trainy = create_subsample(X, y, percentage)
        for model_name in model_names:
            model = model_fit(model_name, trainX, trainy)

            filename = f'{model_name}_base_layer_{i}.sav'
            with open(filename, 'wb') as f:
                pickle.dump(model, f)

        i += 1

def load_model_and_get_BLP(X):
    X = preprocess_the_dataset(X)
    model_names = ['KNN', 'MLP']

    prob = np.zeros((X.shape[0], 1), dtype=float)

    for i in range(10):
        for model_name in model_names:

            filename = f'{model_name}_base_layer_{i}.sav'

            with open(filename, 'rb') as f:
                model = pickle.load(f)

            y_proba = model.predict_proba(X)[:, 1].reshape(-1, 1)
            prob = np.concatenate((prob, y_proba), axis=1)

    prob = np.delete(prob, 0, axis=1)
    return prob

def find_metrics(model_name, y_test):
    if model_name == 'RF':
        model = RandomForestClassifier(random_state=1)
    elif model_name == 'ET':
        model = ExtraTreesClassifier(random_state=1)
    elif model_name == 'DT':
        model = DecisionTreeClassifier(random_state=1)
    elif model_name == 'MLP':
        model = MLPClassifier(random_state=1, max_iter=4000)
    elif model_name == 'LR':
        model = LogisticRegression(class_weight='balanced', random_state=1, max_iter=1000)
    elif model_name == 'NB':
        model = GaussianNB()
    elif model_name == 'KNN':
        model = KNeighborsClassifier()
    elif model_name == 'XGB':
        model = XGBClassifier(random_state=1)
    else:
        print('Wrong model name')
        return

    try:
        model.fit(X_train, y_train)
    except:
        print("Model training failed!")

    y_predict = model.predict(X_test)
    y_proba = model.predict_proba(X_test)


    tn, fp, fn, tp = confusion_matrix(y_test, y_predict).ravel()

    sensitivity = tp / (tp + fn)
    specificity = tn / (tn + fp)

    bal_acc = balanced_accuracy_score(y_test, y_predict)
    acc = accuracy_score(y_test, y_predict)

    if tp == 0 and fp == 0:
        prec = 0
    else:
        prec = tp / (tp + fp)

    if prec == 0 and sensitivity == 0:
        f1_score_1 = 0
    else:
        f1_score_1 = 2 * prec * sensitivity / (prec + sensitivity)
    mcc = matthews_corrcoef(y_test, y_predict)
    auc = roc_auc_score(y_test, y_proba[:, 1])
    auPR = average_precision_score(y_test, y_proba[:, 1])

    return sensitivity, specificity, bal_acc, acc, prec, f1_score_1, mcc, auc, auPR

X = feature_X_Benchmark_embeddings_train.copy()
y = feature_y_Benchmark_embeddings_train.copy()
create_base_layer(X, y)
X = feature_X_Benchmark_embeddings_test.copy()
y = feature_y_Benchmark_embeddings_test.copy()

X = np.concatenate((X, load_model_and_get_BLP(X)), axis=1)

X = preprocess_the_dataset(X)

rus = RandomUnderSampler(random_state=1)
X, y = rus.fit_resample(X, y)

c = Counter(y)
print(c)

all_model_name = ['RF', 'ET', 'DT', 'MLP', 'LR', 'NB', 'KNN', 'XGB']

for model in all_model_name:
    random.seed(1)

    cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)

    local_Sensitivity = []
    local_Specificity = []
    local_Balanced_acc = []
    local_Accuracy = []
    local_Precision = []
    local_AUPR = []
    local_F1 = []
    local_MCC = []
    local_AUC = []

    i = 1
    for train_index, test_index in cv.split(X, y):
        X_train = X[train_index]
        X_test = X[test_index]

        y_train = y[train_index]
        y_test = y[test_index]

        sensitivity, specificity, bal_acc, acc, prec, f1_score_1, mcc, auc, auPR = find_metrics(model, y_test)

        local_Sensitivity.append(sensitivity)
        local_Specificity.append(specificity)
        local_Balanced_acc.append(bal_acc)
        local_Accuracy.append(acc)
        local_Precision.append(prec)
        local_F1.append(f1_score_1)
        local_MCC.append(mcc)
        local_AUC.append(auc)
        local_AUPR.append(auPR)

        print(i, 'th iteration done')
        i = i + 1
        print('___________________________________________________________________________________________________________')

    print('classifier : ', model)
    print('Sensitivity : {0:.3f}'.format(np.mean(local_Sensitivity)))
    print('Specificity : {0:.3f}'.format(np.mean(local_Specificity)))
    print('Balanced_acc : {0:.3f}'.format(np.mean(local_Balanced_acc)))
    print('Accuracy : {0:.3f}'.format(np.mean(local_Accuracy)))
    print('Precision : {0:.3f}'.format(np.mean(local_Precision)))
    print('F1-score: {0:.3f}'.format(np.mean(local_F1)))
    print('MCC: {0:.3f}'.format(np.mean(local_MCC)))
    print('AUC: {0:.3f}'.format(np.mean(local_AUC)))
    print('auPR: {0:.3f}'.format(np.mean(local_AUPR)))

    with open('meta_layer_selection.csv', 'w') as f:
      writer = csv.writer(f)
      writer.writerow(['Classifier', 'Sensitivity', 'Specificity', 'Balanced Accuracy', 'Accuracy', 'Precision', 'F1-score', 'MCC', 'AUC', 'auPR'])

      writer.writerow([model, '{0:.3f}'.format(np.mean(local_Sensitivity)),
                                      '{0:.3f}'.format(np.mean(local_Specificity)),
                                      '{0:.3f}'.format(np.mean(local_Balanced_acc)),
                                      '{0:.3f}'.format(np.mean(local_Accuracy)),
                                      '{0:.3f}'.format(np.mean(local_Precision)), '{0:.3f}'.format(np.mean(local_F1)),
                                      '{0:.3f}'.format(np.mean(local_MCC)), '{0:.3f}'.format(np.mean(local_AUC)),
                                      '{0:.3f}'.format(np.mean(local_AUPR))])
      print('___________________________________________________________________________________________________________')

"""

"""

!pip install optuna

import pandas as pd
import numpy as np
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
import optuna

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split, GridSearchCV

from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB

import random
import pickle
import csv

from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import KBinsDiscretizer

from sklearn.model_selection import StratifiedKFold
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,f1_score,matthews_corrcoef,average_precision_score
from sklearn.metrics import balanced_accuracy_score

def preprocess_the_dataset(feature_X):

    pt = PowerTransformer()
    pt.fit(feature_X)
    feature_X = pt.transform(feature_X)

    return feature_X

feature_X_Benchmark_embeddings_train = np.concatenate((feature_X_Benchmark_embeddings_positive_train, feature_X_Benchmark_embeddings_negative_train), axis=0)
feature_y_Benchmark_embeddings_train = np.concatenate((feature_y_Benchmark_embeddings_positive_train, feature_y_Benchmark_embeddings_negative_train), axis=0)
feature_X_Benchmark_embeddings_test = np.concatenate((feature_X_Benchmark_embeddings_positive_test, feature_X_Benchmark_embeddings_negative_test), axis=0)
feature_y_Benchmark_embeddings_test = np.concatenate((feature_y_Benchmark_embeddings_positive_test, feature_y_Benchmark_embeddings_negative_test), axis=0)

print(feature_X_Benchmark_embeddings_test.shape)
print(feature_y_Benchmark_embeddings_test.shape)

X = feature_X_Benchmark_embeddings_train.copy()
y = feature_y_Benchmark_embeddings_train.copy()

X = preprocess_the_dataset(X)

rus = RandomUnderSampler(random_state=1)
X, y = rus.fit_resample(X, y)

c = Counter(y)
print(c)

"""

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score

def objective(trial):

    hidden_layer_sizes = trial.suggest_categorical('hidden_layer_sizes', [(50, 50), (100, 50), (100,)])
    activation = trial.suggest_categorical('activation', ['tanh', 'relu'])
    solver = trial.suggest_categorical('solver', ['sgd', 'adam'])
    alpha = trial.suggest_float('alpha', 1e-4, 1e-2, log=True)

    clf = MLPClassifier(
        hidden_layer_sizes=hidden_layer_sizes,
        activation=activation,
        solver=solver,
        alpha=alpha,
        random_state=1,
        max_iter=2000
    )

    scoring_metrics = {
        'accuracy': make_scorer(accuracy_score),
        'precision': make_scorer(precision_score, average='macro'),
        'recall': make_scorer(recall_score, average='macro'),
        'f1': make_scorer(f1_score, average='macro')
    }

    scores = {
        metric: cross_val_score(clf, X, y, cv=5, scoring=scoring_metrics[metric]).mean()
        for metric in scoring_metrics
    }

    print(f"Trial {trial.number}: {scores}")

    return scores['accuracy_score']

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

print("Best parameters:", study.best_params)
print("Best f1_score:", study.best_value)

"""

import optuna
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score
import numpy as np

def objective(trial):

    n_neighbors = trial.suggest_int('n_neighbors', 3, 20)
    weights = trial.suggest_categorical('weights', ['uniform', 'distance'])
    metric = trial.suggest_categorical('metric', ['euclidean', 'manhattan'])

    clf = KNeighborsClassifier(n_neighbors=n_neighbors, weights=weights, metric=metric)

    scoring_metrics = {
        'accuracy': make_scorer(accuracy_score),
        'precision': make_scorer(precision_score, average='macro'),
        'recall': make_scorer(recall_score, average='macro'),
        'f1': make_scorer(f1_score, average='macro')
    }

    scores = {
        metric: cross_val_score(clf, X, y, cv=5, scoring=scoring_metrics[metric]).mean()
        for metric in scoring_metrics
    }

    print(f"Trial {trial.number}: {scores}")

    return scores['accuracy_score']

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

print("Best Parameters:", study.best_params)
print("Best f1_score:", study.best_value)



"""

选择了XGB
"""

import pandas as pd
import numpy as np
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split

from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB

import random
import pickle
import csv

from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import KBinsDiscretizer

from sklearn.model_selection import StratifiedKFold
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,f1_score,matthews_corrcoef,average_precision_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.utils.validation import check_is_fitted
from sklearn.exceptions import NotFittedError

def preprocess_the_dataset(feature_X):

    pt = PowerTransformer()
    pt.fit(feature_X)
    feature_X = pt.transform(feature_X)

    return feature_X


def model_fit(model_name, X_train, y_train):
    if model_name == 'RF':
        model = RandomForestClassifier(random_state=1)
    elif model_name == 'ET':
        model = ExtraTreesClassifier(random_state=1)
    elif model_name == 'DT':
        model = DecisionTreeClassifier(random_state=1)
    elif model_name == 'MLP':
        model = MLPClassifier(random_state=1, max_iter=4000, activation='relu', alpha=0, hidden_layer_sizes=(100,50), solver='adam')
    elif model_name == 'LR':
        model = LogisticRegression(class_weight='balanced', random_state=1, max_iter=1000)
    elif model_name == 'NB':
        model = GaussianNB()
    elif model_name == 'KNN':
        model = KNeighborsClassifier(n_neighbors=3, weights='distance', metric='manhattan')
    elif model_name == 'XGB':
        model = XGBClassifier(random_state=1)
    else:
        print('Wrong model name')
        return

    try:
        model.fit(X_train, y_train)

    return model

def make_string(s):
    str = ''
    for i in s:
        str += i + ", "
    return str[:-2]


def create_subsample(X, y, percentage):
    X = np.concatenate((y.reshape(-1, 1), X), axis=1)

    feature_X_positive = X[X[:, 0] == 1, 1:]
    feature_y_positive = X[X[:, 0] == 1, 0].astype('int')

    feature_X_negative = X[X[:, 0] == 0, 1:]
    feature_y_negative = X[X[:, 0] == 0, 0].astype('int')

    feature_X_positive_test = feature_X_positive
    feature_y_positive_test = feature_y_positive

    feature_X_negative_train, feature_X_negative_test, feature_y_negative_train, feature_y_negative_test = train_test_split(
        feature_X_negative, feature_y_negative, test_size=percentage, random_state=1)

    feature_X_test = np.concatenate((feature_X_positive_test, feature_X_negative_test), axis=0)
    feature_y_test = np.concatenate((feature_y_positive_test, feature_y_negative_test), axis=0)

    print("subsample shape:",)
    print(feature_X_test.shape)
    print(feature_y_test.shape)

    return feature_X_test, feature_y_test


def create_base_layer(X, y):
    X = preprocess_the_dataset(X)
    percentages = [0.002, 0.002, 0.002, 0.002, 0.02, 0.02, 0.02, 0.2, 0.2, 0.2]
    model_names = ['KNN', 'MLP']

    i = 0
    for percentage in percentages:
        trainX, trainy = create_subsample(X, y, percentage)
        for model_name in model_names:
            model = model_fit(model_name, trainX, trainy)

            filename = f'{model_name}_base_layer_{i}.sav'
            with open(filename, 'wb') as f:
                pickle.dump(model, f)

        i += 1


def load_model_and_get_BLP(X):
    X = preprocess_the_dataset(X)
    model_names = ['KNN','MLP']

    prob = np.zeros((X.shape[0], 1), dtype=float)
    for itr in range(10):
        for model_name in model_names:
            filename = f'{model_name}_base_layer_{itr}.sav'
            with open(filename, 'rb') as f:
                model = pickle.load(f)
                y_proba = model.predict_proba(X)[:, 1].reshape(-1, 1)
                prob = np.concatenate((prob, y_proba), axis=1)
    prob = np.delete(prob, 0, axis=1)

    return prob

X = feature_X_Benchmark_embeddings_train.copy()
y = feature_y_Benchmark_embeddings_train.copy()
create_base_layer(X, y)

X = feature_X_Benchmark_embeddings_test.copy()
y = feature_y_Benchmark_embeddings_test.copy()
X = np.concatenate((X, load_model_and_get_BLP(X)), axis=1)

rus = RandomUnderSampler(random_state=1)
X, y = rus.fit_resample(X, y)

c = Counter(y)
print(c)

def objective(trial):

    params = {
        'objective': 'binary:logistic',
        'eval_metric': 'logloss',
        'n_estimators': trial.suggest_int('n_estimators', 100, 500),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'lambda': trial.suggest_float('lambda', 1e-5, 10.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-5, 10.0, log=True)
    }

    skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
    metrics = []

    for train_index, test_index in skf.split(X, y):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

        model = XGBClassifier(**params, use_label_encoder=False)
        model.fit(X_train, y_train, verbose=False)

        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        metrics.append(accuracy)

    return np.mean(metrics)

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50)

print("Best hyperparameters:", study.best_params)

final_model = XGBClassifier(**study.best_params, use_label_encoder=False)
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

local_Sensitivity = []
local_Specificity = []
local_Balanced_acc = []
local_Accuracy = []
local_Precision = []
local_F1 = []
local_MCC = []
local_AUC = []
local_auPR = []
local_TP = []
local_TN = []
local_FP = []
local_FN = []

for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    final_model.fit(X_train, y_train, verbose=False)
    y_pred = final_model.predict(X_test)
    y_pred_proba = final_model.predict_proba(X_test)[:, 1]

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    local_TP.append(tp)
    local_TN.append(tn)
    local_FP.append(fp)
    local_FN.append(fn)

    local_Sensitivity.append(tp / (tp + fn))
    local_Specificity.append(tn / (tn + fp))
    local_Accuracy.append(accuracy_score(y_test, y_pred))
    local_Precision.append(precision_score(y_test, y_pred))
    local_F1.append(f1_score(y_test, y_pred))
    local_MCC.append(matthews_corrcoef(y_test, y_pred))
    local_AUC.append(roc_auc_score(y_test, y_pred_proba))
    local_auPR.append(roc_auc_score(y_test, y_pred_proba))

print("Final Metrics")
print("Accuracy: {:.3f}".format(np.mean(local_Accuracy)))
print("Precision: {:.3f}".format(np.mean(local_Precision)))
print("Sensitivity (Recall): {:.3f}".format(np.mean(local_Sensitivity)))
print("Specificity: {:.3f}".format(np.mean(local_Specificity)))
print("F1-score: {:.3f}".format(np.mean(local_F1)))
print("MCC: {:.3f}".format(np.mean(local_MCC)))
print("AUC: {:.3f}".format(np.mean(local_AUC)))
print("auPR: {:.3f}".format(np.mean(local_auPR)))
print("True Positives: {:.3f}".format(np.mean(local_TP)))
print("True Negatives: {:.3f}".format(np.mean(local_TN)))
print("False Positives: {:.3f}".format(np.mean(local_FP)))
print("False Negatives: {:.3f}".format(np.mean(local_FN)))

print("Best hyperparameters:", study.best_params)

"""

def preprocess_the_dataset(feature_X):

    pt = PowerTransformer()
    pt.fit(feature_X)
    feature_X = pt.transform(feature_X)

    return feature_X


def model_fit(model_name, X_train, y_train):
    if model_name == 'RF':
        model = RandomForestClassifier(random_state=1)
    elif model_name == 'ET':
        model = ExtraTreesClassifier(random_state=1)
    elif model_name == 'DT':
        model = DecisionTreeClassifier(random_state=1)
    elif model_name == 'MLP':
        model = MLPClassifier(random_state=1, max_iter=4000, activation='relu', alpha=0, hidden_layer_sizes=(100,50), solver='adam')
    elif model_name == 'LR':
        model = LogisticRegression(class_weight='balanced', random_state=1, max_iter=1000)
    elif model_name == 'NB':
        model = GaussianNB()
    elif model_name == 'KNN':
        model = KNeighborsClassifier(n_neighbors=3, weights='distance', metric='manhattan')
    elif model_name == 'XGB':
        model = XGBClassifier(
    n_estimators=286,
    max_depth=9,
    learning_rate=0.03,
    gamma=0.03,
    subsample=0.76,
    colsample_bytree=0.71,
    reg_alpha=6.17,
    reg_lambda=7.11,
    random_state=1
)

    else:
        print('Wrong model name')
        return

    try:
        model.fit(X_train, y_train)

    return model

def make_string(s):
    str = ''
    for i in s:
        str += i + ", "
    return str[:-2]


def create_subsample(X, y, percentage):
    X = np.concatenate((y.reshape(-1, 1), X), axis=1)

    feature_X_positive = X[X[:, 0] == 1, 1:]
    feature_y_positive = X[X[:, 0] == 1, 0].astype('int')

    feature_X_negative = X[X[:, 0] == 0, 1:]
    feature_y_negative = X[X[:, 0] == 0, 0].astype('int')

    feature_X_positive_test = feature_X_positive
    feature_y_positive_test = feature_y_positive

    feature_X_negative_train, feature_X_negative_test, feature_y_negative_train, feature_y_negative_test = train_test_split(
        feature_X_negative, feature_y_negative, test_size=percentage, random_state=1)

    feature_X_test = np.concatenate((feature_X_positive_test, feature_X_negative_test), axis=0)
    feature_y_test = np.concatenate((feature_y_positive_test, feature_y_negative_test), axis=0)

    print("subsample shape:",)
    print(feature_X_test.shape)
    print(feature_y_test.shape)

    return feature_X_test, feature_y_test


def create_base_layer(X, y):
    X = preprocess_the_dataset(X)
    percentages = [0.002, 0.002, 0.002, 0.002, 0.02, 0.02, 0.02, 0.2, 0.2, 0.2]
    model_names = ['KNN', 'MLP']

    i = 0
    for percentage in percentages:
        trainX, trainy = create_subsample(X, y, percentage)
        for model_name in model_names:
            model = model_fit(model_name, trainX, trainy)

            filename = f'{model_name}_base_layer_{i}.sav'
            with open(filename, 'wb') as f:
                pickle.dump(model, f)

        i += 1


def create_meta_layer(X, y):

    trainX, trainy = X, y

    model = XGBClassifier(
        n_estimators=286,
    max_depth=9,
    learning_rate=0.03,
    gamma=0.03,
    subsample=0.76,
    colsample_bytree=0.71,
    reg_alpha=6.17,
    reg_lambda=7.11,
    random_state=1
    )

    model.fit(trainX, trainy)

    filename = 'XGB_meta_layer.sav'
    with open(filename, 'wb') as f:
        pickle.dump(model, f)



def load_model_and_get_BLP(X):
    X = preprocess_the_dataset(X)
    model_names = ['KNN','MLP']

    prob = np.zeros((X.shape[0], 1), dtype=float)
    for itr in range(10):
        for model_name in model_names:
            filename = f'{model_name}_base_layer_{itr}.sav'
            with open(filename, 'rb') as f:
                model = pickle.load(f)
                y_proba = model.predict_proba(X)[:, 1].reshape(-1, 1)
                prob = np.concatenate((prob, y_proba), axis=1)
    prob = np.delete(prob, 0, axis=1)

    return prob

from sklearn.preprocessing import PowerTransformer


X = feature_X_Benchmark_embeddings_test.copy()
y = feature_y_Benchmark_embeddings_test.copy()
X = np.concatenate((X, load_model_and_get_BLP(X)), axis=1)

print(X.shape)
print(y.shape)

X = preprocess_the_dataset(X)

rus = RandomUnderSampler(random_state=1)
X, y = rus.fit_resample(X, y)

c = Counter(y)
print(c)

create_meta_layer(X, y)

"""

def preprocess_the_dataset(feature_X):

    pt = PowerTransformer()
    pt.fit(feature_X)
    feature_X = pt.transform(feature_X)

    return feature_X


def make_string(s):
    str = ''
    for i in s:
        str += i + ", "
    return str[:-2]


def load_the_pickle_files_base_layer(converted_all_features_with_output):
    test_X = preprocess_the_dataset(converted_all_features_with_output)
    test_base_output_total = np.zeros((len(test_X), 1), dtype=float)

    pickle_folder_path = str('/content/')

    base_classifiers = ['KNN', 'MLP']

    for i in range(0, 10):
        for base_classifier in base_classifiers:

            pickle_file_path = str(pickle_folder_path + base_classifier + '_base_layer_' + str(i) + '.sav')

            with open(pickle_file_path, 'rb') as outfile:
                model = pickle.load(outfile)

            y_proba = model.predict_proba(test_X)[:, 1].reshape(-1, 1)
            test_base_output_total = np.concatenate((test_base_output_total, y_proba), axis=1)

    test_base_output_total = np.delete(test_base_output_total, 0, axis=1)

    return test_base_output_total



def load_the_pickle_files_meta_layer(converted_all_features_with_output):
    test_X = preprocess_the_dataset(converted_all_features_with_output)

    pickle_file_path = '/content/XGB_meta_layer.sav'

    with open(pickle_file_path, 'rb') as outfile:
        clf = pickle.load(outfile)

    y_pred = clf.predict(test_X)
    y_prob = clf.predict_proba(test_X)

    return y_pred, y_prob


def find_metrics(y_predict, y_proba, y_test):

    tn, fp, fn, tp = confusion_matrix(y_test, y_predict).ravel()

    sensitivity = tp / (tp + fn)
    specificity = tn / (tn + fp)

    bal_acc = balanced_accuracy_score(y_test, y_predict)
    acc = accuracy_score(y_test, y_predict)

    if tp == 0 and fp == 0:
        prec = 0
    else:
        prec = tp / (tp + fp)

    if prec == 0 and sensitivity == 0:
        f1_score_1 = 0
    else:
        f1_score_1 = 2 * prec * sensitivity / (prec + sensitivity)
    mcc = matthews_corrcoef(y_test, y_predict)
    auc = roc_auc_score(y_test, y_proba[:, 1])
    auPR = average_precision_score(y_test, y_proba[:, 1])

    return sensitivity, specificity, bal_acc, acc, prec, f1_score_1, mcc, auc, auPR

with open('metrics_TS129.csv', 'w') as f:
    writer = csv.writer(f)
    writer.writerow(['Predictor', 'Sensitivity', 'Specificity', 'Balanced_acc',
                     'Accuracy', 'F1-score', 'MCC', 'AUC', 'auPR'])

    D_feature = pd.read_csv('/content/merged_output_129.csv')
    feature_y_Benchmark = D_feature.iloc[:, 0].values
    feature_X_Benchmark = D_feature.iloc[:, 2:1026].values

    X = feature_X_Benchmark.copy()
    X = preprocess_the_dataset(X)
    y = feature_y_Benchmark.copy()

    print('X : ', X.shape)
    print('y : ', y.shape)

    BLP = load_the_pickle_files_base_layer(X)
    X = np.concatenate((X, BLP), axis=1)

    print('X : ', X.shape)
    print('y : ', y.shape)

    y_pred, y_proba = load_the_pickle_files_meta_layer(X)

    sensitivity, specificity, bal_acc, acc, prec, f1_score_1, mcc, auc, auPR = find_metrics(y_pred, y_proba, y)

    print('Sensitivity : {0:.3f}'.format(sensitivity))
    print('Specificity : {0:.3f}'.format(specificity))
    print('Balanced_acc : {0:.3f}'.format(bal_acc))
    print('Accuracy : {0:.3f}'.format(acc))
    print('F1-score: {0:.3f}'.format(f1_score_1))
    print('MCC: {0:.3f}'.format(mcc))
    print('AUC: {0:.3f}'.format(auc))
    print('auPR: {0:.3f}'.format(auPR))

    writer.writerow(['Stackmodel', '{0:.3f}'.format(sensitivity), '{0:.3f}'.format(specificity), '{0:.3f}'.format(bal_acc), '{0:.3f}'.format(acc), '{0:.3f}'.format(f1_score_1), '{0:.3f}'.format(mcc), '{0:.3f}'.format(auc), '{0:.3f}'.format(auPR)])

with open('metrics_TS129.csv', 'w') as f:
    writer = csv.writer(f)
    writer.writerow(['Predictor', 'Sensitivity', 'Specificity', 'Balanced_acc',
                     'Accuracy', 'F1-score', 'MCC', 'AUC', 'auPR'])

    D_feature = pd.read_csv('/content/merged_output_129.csv')
    feature_y_Benchmark = D_feature.iloc[:, 0].values
    feature_X_Benchmark = D_feature.iloc[:, 2:1026].values

    X = feature_X_Benchmark.copy()
    X = preprocess_the_dataset(X)
    y = feature_y_Benchmark.copy()

    print('X : ', X.shape)
    print('y : ', y.shape)

    BLP = load_the_pickle_files_base_layer(X)
    X = np.concatenate((X, BLP), axis=1)

    print('X : ', X.shape)
    print('y : ', y.shape)

    y_pred, y_proba = load_the_pickle_files_meta_layer(X)

    results_df = pd.DataFrame({
    "True_Label": y,
    "Predicted_Label": y_pred,
    "Predicted_Probability": [max(prob) for prob in y_proba]
})


    X_df = pd.DataFrame(X, columns=[f"Feature_{i}" for i in range(X.shape[1])])
    results_df = pd.concat([X_df, results_df], axis=1)

    results_file = "detailed_predictions.csv"
    results_df.to_csv(results_file, index=False)

    print(f"详细预测结果已保存到文件：{results_file}")

detailed_predictions=pd.read_csv("/content/detailed_predictions.csv")

detailed_predictions.head()

detailed_predictions.shape

"""

import os

pdb_folder_path = "/content/drive/MyDrive/AF2_predicted_pdb"

pdb_files = [f for f in os.listdir(pdb_folder_path) if f.endswith(".pdb")]

for pdb_file in pdb_files[:3]:
    print(f"文件名: {pdb_file}")
    pdb_path = os.path.join(pdb_folder_path, pdb_file)

    with open(pdb_path, "r") as file:
        lines = file.readlines()
        for line in lines[:10]:
            print(line.strip())
    print("-" * 50)

!pip install biopython

"""

from Bio.PDB import PDBParser
import os
import pandas as pd


def calculate_residue_center(residue):
    atoms = residue.get_atoms()
    coords = [atom.coord for atom in atoms]
    center = np.mean(coords, axis=0)
    return center

def extract_pdb_features_from_folder(pdb_folder):
    parser = PDBParser(QUIET=True)
    all_features = []

    for pdb_file in os.listdir(pdb_folder):
        if pdb_file.endswith('.pdb'):
            pdb_path = os.path.join(pdb_folder, pdb_file)
            structure = parser.get_structure(pdb_file, pdb_path)

            for model in structure:
                for chain in model:
                    for residue in chain:
                        if residue.id[0] == ' ':
                            center = calculate_residue_center(residue)

                            pdb_id = pdb_file.split('.')[0]
                            residue_id = f"{pdb_id}_{residue.id[1]}"
                            residue_name = residue.resname
                            all_features.append([residue_id, residue_name, center[0], center[1], center[2]])

    pdb_features = pd.DataFrame(all_features, columns=['ResidueID', 'ResidueName', 'Center_X', 'Center_Y', 'Center_Z'])
    return pdb_features

pdb_folder_path = "/content/drive/MyDrive/AF2_predicted_pdb"
pdb_features = extract_pdb_features_from_folder(pdb_folder_path)
print("修正后的 PDB 数据示例：")
print(pdb_features.head())

embedding_data = pd.read_csv("/content/merged_output_129.csv")

embedding_data.head()

embedding_data.shape

pdb_features.head()

embedding_data['Residue_Number'] = embedding_data.groupby('ProteinID').cumcount() + 1

embedding_data['ResidueID'] = embedding_data['ProteinID'] + "_" + embedding_data['Residue_Number'].astype(str)

embedding_data['ResidueID'] = embedding_data['ResidueID'].str.strip().str.upper()
pdb_features['ResidueID'] = pdb_features['ResidueID'].str.strip().str.upper()

print("Embedding 数据 ResidueID 示例:", embedding_data['ResidueID'].unique()[:5])
print("PDB 数据 ResidueID 示例:", pdb_features['ResidueID'].unique()[:5])

"""

embedding_data = embedding_data.sort_index()
detailed_predictions = detailed_predictions.sort_index()

merged_data_129 = pd.concat([embedding_data, detailed_predictions], axis=1)

merged_data_129 = merged_data.loc[:, ~merged_data.columns.duplicated()]

print("合并后的数据形状：", merged_data_129.shape)
print(merged_data_129.head())

merged_data = pd.merge(merged_data_129, pdb_features, on='ResidueID', how='inner')

print("合并后的数据形状:", merged_data.shape)
print(merged_data.head())

if 'ResidueID' in merged_data.columns:
    print("ResidueID 列存在于 merged_data 中。")
else:
    print("ResidueID 列不存在于 merged_data 中。")

output_path = "/content/drive/MyDrive/论文/merged_pdb_embedding_data_129.csv"
merged_data.to_csv(output_path, index=False)

print(f"数据已保存至 {output_path}")

merged_data.head()

merged_data.shape

!pip install torch torch_geometric

import pandas as pd
merged_data=pd.read_csv("/content/drive/MyDrive/论文/merged_pdb_embedding_data_129.csv")

import networkx as nx
from scipy.sparse import csr_matrix

import numpy as np

coords = merged_data[["Center_X", "Center_Y", "Center_Z"]].values
threshold = 4.5

neighbor_count = []
for i in range(len(coords)):
    distances = np.linalg.norm(coords - coords[i], axis=1)
    neighbor_count.append(np.sum(distances <= threshold))

merged_data["Neighbor_Count"] = neighbor_count

centroid = np.mean(coords, axis=0)
merged_data["Centroid_Distance"] = np.linalg.norm(coords - centroid, axis=1)

errors = merged_data[merged_data["Label"] != merged_data["Predicted_Label"]]

import seaborn as sns
import matplotlib.pyplot as plt

sns.scatterplot(data=errors, x="Neighbor_Count", y="Centroid_Distance", hue="True_Label")
plt.title("Error Analysis with Geometry Features")
plt.xlabel("Neighbor Count")
plt.ylabel("Centroid Distance")
plt.legend(title="True Label")
plt.show()

from sklearn.utils import resample

majority = errors[errors["True_Label"] == 0]
minority = errors[errors["True_Label"] == 1]

majority_downsampled = resample(majority, replace=False, n_samples=len(minority), random_state=42)
balanced_errors = pd.concat([majority_downsampled, minority])

sns.scatterplot(data=balanced_errors, x="Neighbor_Count", y="Centroid_Distance", hue="True_Label")
plt.title("Balanced Error Analysis")
plt.xlabel("Neighbor Count")
plt.ylabel("Centroid Distance")
plt.show()

sns.scatterplot(data=errors, x="Neighbor_Count", y="Centroid_Distance", hue="True_Label", alpha=0.4)
plt.title("Error Analysis with Geometry Features (Adjusted Transparency)")
plt.xlabel("Neighbor Count")
plt.ylabel("Centroid Distance")
plt.show()

sns.kdeplot(data=errors[errors["True_Label"] == 0], x="Neighbor_Count", y="Centroid_Distance", fill=True, cmap="Blues", alpha=0.6)
sns.kdeplot(data=errors[errors["True_Label"] == 1], x="Neighbor_Count", y="Centroid_Distance", fill=True, cmap="Oranges", alpha=0.6)
plt.title("Density Distribution of Error Samples")
plt.xlabel("Neighbor Count")
plt.ylabel("Centroid Distance")
plt.show()

"""

!pip install torch torchvision torchaudio torch-geometric

merged_data=pd.read_csv("/content/drive/MyDrive/论文/merged_pdb_embedding_data_573.csv")

merged_data.head()






feature_y = merged_data['Label'].values
feature_X = merged_data.iloc[:, -3:].values

original_indices = np.arange(len(feature_y))

positive_mask = feature_y == 1
negative_mask = feature_y == 0

feature_X_positive = feature_X[positive_mask]
feature_y_positive = feature_y[positive_mask]
positive_indices = original_indices[positive_mask]

feature_X_negative = feature_X[negative_mask]
feature_y_negative = feature_y[negative_mask]
negative_indices = original_indices[negative_mask]


feature_X_positive_train, feature_X_positive_test, feature_y_positive_train, feature_y_positive_test, positive_train_indices, positive_test_indices = train_test_split(
    feature_X_positive, feature_y_positive, positive_indices, test_size=0.3, random_state=1)

feature_X_negative_train, feature_X_negative_test, feature_y_negative_train, feature_y_negative_test, negative_train_indices, negative_test_indices = train_test_split(
    feature_X_negative, feature_y_negative, negative_indices, test_size=0.3, random_state=1)

feature_X_train = np.concatenate((feature_X_positive_train, feature_X_negative_train), axis=0)
feature_y_train = np.concatenate((feature_y_positive_train, feature_y_negative_train), axis=0)
train_indices = np.concatenate((positive_train_indices, negative_train_indices), axis=0)

feature_X_test = np.concatenate((feature_X_positive_test, feature_X_negative_test), axis=0)
feature_y_test = np.concatenate((feature_y_positive_test, feature_y_negative_test), axis=0)
test_indices = np.concatenate((positive_test_indices, negative_test_indices), axis=0)

print("训练集大小:", feature_X_train.shape, feature_y_train.shape)
print("测试集大小:", feature_X_test.shape, feature_y_test.shape)
print("训练集索引:", train_indices)
print("测试集索引:", test_indices)

print(feature_X[:10])

print(feature_X_positive.shape)
print(feature_y_positive.shape)
print(feature_X_negative.shape)
print(feature_y_negative.shape)

from sklearn.neighbors import KDTree
import torch

threshold = 4.5

tree = KDTree(feature_X_train)
neighbors = tree.query_radius(feature_X_train, r=threshold)

edge_index = []
for i, neighbor_indices in enumerate(neighbors):
    for j in neighbor_indices:
        if i != j:
            edge_index.append([i, j])

edge_index = torch.tensor(edge_index, dtype=torch.long).T
print("Edge Index Shape:", edge_index.shape)

from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=1, replacement=False)
X_balanced, y_balanced = rus.fit_resample(feature_X_train, feature_y_train)

balanced_indices = rus.sample_indices_

print(f"Original train data size: {feature_X_train.shape[0]}")
print(f"Balanced train data size: {X_balanced.shape[0]}")
print(f"Balanced X shape: {X_balanced.shape}")
print(f"Balanced y shape: {y_balanced.shape}")


train_index_mapping = {old_idx: new_idx for new_idx, old_idx in enumerate(balanced_indices)}
test_index_mapping = {old_idx: new_idx for new_idx, old_idx in enumerate(test_indices)}

train_new_edge_index = []
test_new_edge_index = []

for i, j in edge_index.T.numpy():

    if i in train_index_mapping and j in train_index_mapping:
        train_new_edge_index.append([train_index_mapping[i], train_index_mapping[j]])

    if i in test_index_mapping and j in test_index_mapping:
        test_new_edge_index.append([test_index_mapping[i], test_index_mapping[j]])

train_new_edge_index = torch.tensor(train_new_edge_index, dtype=torch.long).T
test_new_edge_index = torch.tensor(test_new_edge_index, dtype=torch.long).T

print("Train Edge Index Shape:", train_new_edge_index.shape)
print("Test Edge Index Shape:", test_new_edge_index.shape)

from torch_geometric.data import Data
import torch

train_data = Data(
    x=torch.tensor(X_balanced, dtype=torch.float),
    edge_index=train_new_edge_index,
    y=torch.tensor(y_balanced, dtype=torch.long)
)

test_data = Data(
    x=torch.tensor(feature_X_test, dtype=torch.float),
    edge_index=test_new_edge_index,
    y=torch.tensor(feature_y_test, dtype=torch.long)
)

!pip install torch-geometric

import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class GCN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim=1, dropout=0.5):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.dropout = dropout

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = F.relu(self.conv1(x, edge_index))
        x = F.dropout(x, p=self.dropout, training=self.training)
        x = F.relu(self.conv2(x, edge_index))
        x = F.dropout(x, p=self.dropout, training=self.training)
        x = self.fc(x)
        return x

from torch.optim import Adam
from torch.nn import BCEWithLogitsLoss

model = GCN(input_dim=train_data.x.shape[1], hidden_dim=64, output_dim=1)
optimizer = Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = BCEWithLogitsLoss()

num_epochs = 50
for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()

    train_output = model(train_data)
    train_loss = criterion(train_output.squeeze(), train_data.y.float())

    train_loss.backward()
    optimizer.step()

    print(f"Epoch {epoch + 1}/{num_epochs}, Train Loss: {train_loss.item():.4f}")



model = GCN(input_dim=train_data.x.shape[1], hidden_dim=64, output_dim=1)
optimizer = Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = BCEWithLogitsLoss()

num_epochs = 50
for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()

    train_output = model(train_data)
    train_loss = criterion(train_output.squeeze(), train_data.y.float())

    train_loss.backward()
    optimizer.step()

    print(f"Epoch {epoch + 1}/{num_epochs}, Train Loss: {train_loss.item():.4f}")

model.eval()
with torch.no_grad():
    test_output = model(test_data)
    test_loss = criterion(test_output.squeeze(), test_data.y.float())

    test_preds = torch.sigmoid(test_output).cpu().numpy()
    test_preds = (test_preds > 0.5).astype(int)

    print(f"Test Loss: {test_loss.item():.4f}")

from sklearn.metrics import accuracy_score, recall_score, f1_score, roc_auc_score, precision_recall_curve, auc, matthews_corrcoef
test_labels = test_data.y.cpu().numpy()

accuracy = accuracy_score(test_labels, test_preds)
recall = recall_score(test_labels, test_preds)
specificity = recall_score(test_labels, test_preds, pos_label=0)
f1 = f1_score(test_labels, test_preds)
mcc = matthews_corrcoef(test_labels, test_preds)
auc_roc = roc_auc_score(test_labels, test_output)

precision, recall_vals, _ = precision_recall_curve(test_labels, test_output)
auc_pr = auc(recall_vals, precision)

print(f"Accuracy: {accuracy:.4f}")
print(f"Sensitivity/Recall: {recall:.4f}")
print(f"Specificity: {specificity:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"MCC: {mcc:.4f}")
print(f"AUC-ROC: {auc_roc:.4f}")
print(f"AUC-PR: {auc_pr:.4f}")

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve

fpr, tpr, _ = roc_curve(test_labels, torch.sigmoid(test_output).cpu().numpy())
plt.plot(fpr, tpr, label="ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Receiver Operating Characteristic (ROC)")
plt.legend()
plt.show()

from sklearn.metrics import precision_recall_curve

precision, recall, _ = precision_recall_curve(test_labels, torch.sigmoid(test_output).cpu().numpy())
plt.plot(recall, precision, label="Precision-Recall Curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()
plt.show()

import optuna
from torch.optim import Adam
from torch.nn import BCEWithLogitsLoss

def validate(model, test_data, criterion):
    model.eval()
    with torch.no_grad():
        test_output = model(test_data)
        test_loss = criterion(test_output.squeeze(), test_data.y.float())
    return test_loss.item()

def objective(trial):

    hidden_dim = trial.suggest_categorical("hidden_dim", [64, 128, 256])
    lr = trial.suggest_loguniform("lr", 1e-4, 1e-2)
    dropout = trial.suggest_uniform("dropout", 0.1, 0.5)

    input_dim = train_data.x.shape[1]
    model = GCN(input_dim=input_dim, hidden_dim=hidden_dim, output_dim=1)
    optimizer = Adam(model.parameters(), lr=lr)
    criterion = BCEWithLogitsLoss()

    model.train()
    for epoch in range(50):
        optimizer.zero_grad()
        train_output = model(train_data)
        train_loss = criterion(train_output.squeeze(), train_data.y.float())
        train_loss.backward()
        optimizer.step()

    val_loss = validate(model, test_data, criterion)
    return val_loss

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=50)
print("Best hyperparameters:", study.best_params)

!pip install optuna

"""

"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class AttentionLayer(nn.Module):
    def __init__(self, input_dim):
        super(AttentionLayer, self).__init__()
        self.attention_weights = nn.Linear(input_dim * 2, 1)

    def forward(self, blp, gcn_output):

        combined = torch.cat((blp, gcn_output), dim=1)

        alpha = torch.sigmoid(self.attention_weights(combined))

        output = alpha * blp + (1 - alpha) * gcn_output

        return output, alpha

class MetaLayer(nn.Module):
    def __init__(self, input_dim, attention_dim, output_dim):
        super(MetaLayer, self).__init__()
        self.fc1 = nn.Linear(input_dim + attention_dim, 128)
        self.fc2 = nn.Linear(128, output_dim)

    def forward(self, embedding_data, attention_output):
        combined = torch.cat((embedding_data, attention_output), dim=1)
        x = F.relu(self.fc1(combined))
        output = torch.sigmoid(self.fc2(x))
        return output

class StackedAttentionModel(nn.Module):
    def __init__(self, blp_dim, gcn_dim, embedding_dim, meta_output_dim):
        super(StackedAttentionModel, self).__init__()
        self.attention_layer = AttentionLayer(blp_dim)
        self.meta_layer = MetaLayer(embedding_dim, blp_dim, meta_output_dim)

    def forward(self, blp, gcn_output, embedding_data):

        attention_output, attention_weights = self.attention_layer(blp, gcn_output)

        output = self.meta_layer(embedding_data, attention_output)
        return output, attention_weights

import pickle
BLP_train = load_model_and_get_BLP(X_embedding_train)

from joblib import dump

dump(BLP_train, 'BLP_train.joblib')
print("BLP_train 已成功保存到本地！")

X = np.concatenate((X_embedding_train, BLP_train), axis=1)
y_pred, y_proba = load_the_pickle_files_meta_layer(X)

results_df = pd.DataFrame({
    "True_Label": y_train,
    "Predicted_Label": y_pred,
    "Predicted_Probability": [max(prob) for prob in y_proba]
})

results_file = "embedding train_predictions.csv"
results_df.to_csv(results_file, index=False)

print(f"详细预测结果已保存到文件：{results_file}")

results_df.head()

misclassified_indices = results_df.index[results_df['True_Label'] != results_df['Predicted_Label']]

plt.figure(figsize=(10, 6))
plt.hist(results_df.loc[misclassified_indices, 'Predicted_Probability'], bins=50, alpha=0.7, color='red', label='Misclassified')
plt.hist(results_df['Predicted_Probability'], bins=50, alpha=0.5, color='blue', label='All Samples')
plt.xlabel("Predicted Probability")
plt.ylabel("Frequency")
plt.legend()
plt.title("Distribution of Predicted Probabilities for Misclassified Samples")
plt.grid(True)
plt.show()

merged_data=pd.read_csv("/content/drive/MyDrive/论文/merged_pdb_embedding_data_573.csv")

from sklearn.model_selection import train_test_split

X_embedding = merged_data.iloc[:, 3:1027].values
X_structure = merged_data.iloc[:, -3:].values
y = merged_data.iloc[:, 0].values

X_embedding_train, X_embedding_val, X_structure_train, X_structure_val, y_train, y_val = train_test_split(
    X_embedding, X_structure, y, test_size=0.3, random_state=1
)

print(f"X_embedding_train shape: {X_embedding_train.shape}")
print(f"X_embedding_val shape: {X_embedding_val.shape}")
print(f"X_structure_train shape: {X_structure_train.shape}")
print(f"X_structure_val shape: {X_structure_val.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_val shape: {y_val.shape}")

positive_indices = (y_train == 1)
negative_indices = (y_train == 0)
X_pdb_positive = X_structure_train[positive_indices]
X_pdb_negative = X_structure_train[negative_indices]
y_positive = y_train[positive_indices]
y_negative = y_train[negative_indices]
print(f"正样本数量: {len(y_positive)}, 特征维度: {X_pdb_positive.shape[1]}")
print(f"负样本数量: {len(y_negative)}, 特征维度: {X_pdb_negative.shape[1]}")

from scipy.spatial.distance import pdist, squareform
import numpy as np
import matplotlib.pyplot as plt

sample_ratio = 0.1
negative_sample_size = int(len(X_pdb_negative) * sample_ratio)

np.random.seed(1)
sampled_negative_indices = np.random.choice(len(X_pdb_negative), negative_sample_size, replace=False)
sampled_negative_coords = X_pdb_negative[sampled_negative_indices]

distance_matrix_P = squareform(pdist(X_pdb_positive))
distances_P = distance_matrix_P[np.triu_indices_from(distance_matrix_P, k=1)]

distance_matrix_N = squareform(pdist(sampled_negative_coords))
distances_N = distance_matrix_N[np.triu_indices_from(distance_matrix_N, k=1)]

plt.figure(figsize=(10, 6))
plt.hist(distances_P, bins=50, alpha=0.7, color='blue', label='Positive Samples')
plt.hist(distances_N, bins=50, alpha=0.7, color='red', label='Negative Samples (Sampled)')
plt.xlabel("Distance (Å)")
plt.ylabel("Frequency")
plt.title("Distribution of Pairwise Distances for Positive and Negative Samples")
plt.legend()
plt.grid()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.hist(distances_P, bins=50, alpha=0.7, color='blue', label='Positive Samples')
plt.hist(distances_N, bins=50, alpha=0.7, color='red', label='Negative Samples')
plt.xlabel("Distance (Å)")
plt.ylabel("Frequency")
plt.title("Distribution of Pairwise Distances for Positive and Negative Samples")
plt.legend()
plt.grid()
plt.show()

from sklearn.neighbors import KDTree
import torch

threshold = 4

tree = KDTree(X_pdb_positive)
neighbors = tree.query_radius(X_pdb_positive, r=threshold)

edge_index = []
for i, neighbor_indices in enumerate(neighbors):
    for j in neighbor_indices:
        if i != j:
            edge_index.append([i, j])

edge_index = torch.tensor(edge_index, dtype=torch.long).T
print("Edge Index Shape:", edge_index.shape)

num_neighbors = torch.bincount(edge_index[0])

print(f"平均邻居数: {num_neighbors.float().mean():.2f}")
print(f"最大邻居数: {num_neighbors.max().item()}")
print(f"最小邻居数: {num_neighbors.min().item()}")

from torch_geometric.data import Data
import torch
from torch_geometric.data import Data

graph_data = Data(
    x=torch.tensor(X_pdb_positive, dtype=torch.float),
    edge_index=edge_index,
    y=torch.tensor(y_train[positive_indices], dtype=torch.long)
)

print(graph_data)

import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class GCN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim=1, dropout=0.5):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.fc = nn.Linear(hidden_dim, output_dim)
        self.dropout = dropout

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

input_dim = graph_data.num_node_features
hidden_dim = 32
output_dim = 2

gcn_model = GCN(input_dim, hidden_dim, output_dim)
print(gcn_model)

from torch_geometric.loader import DataLoader
from torch.optim import Adam

loader = DataLoader([graph_data], batch_size=1, shuffle=True)

optimizer = Adam(gcn_model.parameters(), lr=0.01, weight_decay=5e-4)

gcn_model.train()
for epoch in range(50):
    for batch in loader:
        optimizer.zero_grad()
        out = gcn_model(batch.x, batch.edge_index)
        loss = F.nll_loss(out, batch.y)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch + 1}, Loss: {loss.item():.4f}")

gcn_model.eval()

out = gcn_model(graph_data.x, graph_data.edge_index)
predictions = out.argmax(dim=1)

print("预测类别：", predictions.tolist())

results_df=pd.read_csv("/content/embedding train_predictions.csv")

results_df['Probability_Adjusted'] = results_df.apply(
    lambda row: 1 - row['Predicted_Probability'] if row['Predicted_Label'] == 0 else row['Predicted_Probability'],
    axis=1
)

results_df.head()

results_df.shape

merged_data.head()

merged_data.shape

X_structure_train.shape

result_train_positive = results_df[positive_indices]

result_train_positive.shape

result_train_positive.head()

X_pdb_positive.head()

misclassified_indices = results_df.index[results_df['True_Label'] != results_df['Predicted_Label']]

plt.figure(figsize=(10, 6))
plt.hist(results_df.loc[misclassified_indices, 'Probability_Adjusted'], bins=50, alpha=0.7, color='red', label='Misclassified')
plt.hist(results_df['Probability_Adjusted'], bins=50, alpha=0.5, color='blue', label='All Samples')
plt.xlabel("Probability_Adjusted")
plt.ylabel("Frequency")
plt.legend()
plt.title("Distribution of Predicted Probabilities for Misclassified Samples")
plt.grid(True)
plt.show()

low_confidence_threshold = 0.3

low_confidence_indices = result_train_positive.index[result_train_positive['Probability_Adjusted'] < low_confidence_threshold]

low_confidence_features = torch.tensor(X_structure_train[low_confidence_indices], dtype=torch.float)

print(f"Low Confidence Samples: {len(low_confidence_indices)}")

low_confidence_indices

low_confidence_node_map = {old_idx: new_idx for new_idx, old_idx in enumerate(low_confidence_indices)}

filtered_edge_index = []
for src, dst in edge_index.T.tolist():
    if src in low_confidence_node_map and dst in low_confidence_node_map:
        filtered_edge_index.append([
            low_confidence_node_map[src],
            low_confidence_node_map[dst]
        ])

filtered_edge_index = torch.tensor(filtered_edge_index, dtype=torch.long).T
print(f"Filtered Edge Index Shape: {filtered_edge_index.shape}")

gcn_model.eval()

low_confidence_predictions = gcn_model(low_confidence_features, filtered_edge_index).argmax(dim=1).numpy()

print(f"Low Confidence Predictions Shape: {low_confidence_predictions.shape}")

results_df.loc[low_confidence_indices, 'Updated_Predicted_Label'] = (low_confidence_predictions > 0.5).astype(int)

original_accuracy = (results_df['Predicted_Label'] == results_df['True_Label']).mean()
updated_accuracy = (results_df[
'Updated_Predicted_Label'].fillna(results_df['Predicted_Label']) == results_df['True_Label']).mean()
print(f"Original Accuracy: {original_accuracy:.4f}")
print(f"Updated Accuracy: {updated_accuracy:.4f}")
print(f"Accuracy Improvement: {updated_accuracy - original_accuracy:.4f}")

original_correct = (result_train_positive['Predicted_Label'] == result_train_positive['True_Label']).sum()

original_accuracy = original_correct / len(result_train_positive)
print(f"Original Accuracy: {original_accuracy:.4f}")

result_train_positive['Final_Predicted_Label'] = result_train_positive['Updated_Predicted_Label'].fillna(result_train_positive['Predicted_Label'])

updated_correct = (result_train_positive['Final_Predicted_Label'] == result_train_positive['True_Label']).sum()

updated_accuracy = updated_correct / len(result_train_positive)
print(f"Updated Accuracy: {updated_accuracy:.4f}")

accuracy_improvement = updated_accuracy - original_accuracy
print(f"Accuracy Improvement: {accuracy_improvement:.4f}")

